export { default as GET_CONFIGS_QUERY } from './GET_CONFIGS_QUERY'
export {
  default as GET_CONFIG_EXECUTIONS_QUERY,
} from './GET_CONFIG_EXECUTIONS_QUERY'
export { default as GET_PROJECT_BY_SLUG_QUERY } from './GET_PROJECT_BY_SLUG_QUERY'
export { default as GET_PROJECTS_QUERY } from './GET_PROJECTS_QUERY'
export {
  default as GET_PROJECT_EXECUTIONS_QUERY,
} from './GET_PROJECT_EXECUTIONS_QUERY'
export { default as GET_REPOSITORIES_QUERY } from './GET_REPOSITORIES_QUERY'
